#!/bin/bash

declare -r CURRENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

  "chmod +x ${CURRENT_DIR}/ResidualVM_unstable_20151008/residualvm_i386"
  "${CURRENT_DIR}/ResidualVM_unstable_20151008/residualvm_i386" "$@"

